services:
  ottos-stand-service:
    build:
      context: ./ottos-stand-service
      dockerfile: Dockerfile.dev
    container_name: ottos-stand-service
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_MQ_CONNECTION_STRING=amqp://rabbitmq:5672
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./ottos-stand-service:/app
      - /app/node_modules
    command: npm run start:dev
    tty: true
  postman-service:
    build:
      context: ./postman-service
      dockerfile: Dockerfile.dev
    container_name: postman-service
    depends_on:
      - rabbitmq
      - ottos-stand-service
    environment:
      - RABBIT_MQ_CONNECTION_STRING=amqp://rabbitmq:5672
    ports:
      - "3001:3000"
    volumes:
      - ./postman-service:/app
      - /app/node_modules
    command: npm run start:dev
    tty: true
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  rabbitmq_data:
