services:
  ottos-stand-service:
    build:
      context: ./ottos-stand-service
      dockerfile: Dockerfile.dev
    container_name: ottos-stand-service
    depends_on:
      - rabbitmq
    environment:
      - PORT=3000
      - RABBIT_MQ_CONNECTION_STRING=amqp://rabbitmq:5672
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    ports:
      - "3000:3000"
    volumes:
      - ./ottos-stand-service:/app
      - /app/node_modules
    command: npm run start:dev
    tty: true
  carlos-background-service:
    build:
      context: ./carlos-background-service
      dockerfile: Dockerfile.dev
    container_name: carlos-background-service
    depends_on:
      - rabbitmq
    environment:
      - RABBIT_MQ_CONNECTION_STRING=amqp://rabbitmq:5672
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    volumes:
      - ./carlos-background-service:/app
      - /app/node_modules
    command: npm run start:dev
    tty: true
  postman-service:
    build:
      context: ./postman-service
      dockerfile: Dockerfile.dev
    container_name: postman-service
    depends_on:
      - rabbitmq
      - ottos-stand-service
    environment:
      - RABBIT_MQ_CONNECTION_STRING=amqp://rabbitmq:5672
      - PORT=3000
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    ports:
      - "3001:3000"
    volumes:
      - ./postman-service:/app
      - /app/node_modules
    command: npm run start:dev
    tty: true
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
  postgres_db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  rabbitmq_data:
  postgres_data:
