replicaCount: 3

image:
  repository: rabbitmq-consumer
  tag: latest
  pullPolicy: Never

containerPort: 3000
nodePort: 30001

env:
  RABBIT_MQ_CONNECTION_STRING: amqp://default_user_3ZCowrj7c_X9b9iJf-F:7lZhIO06ZesrPc1nVaiWSSqQgbWf1NO-@rabbitmq-mediator
